name: Stage the application

on:
  pull_request:
    types: [labeled]

env:
  AZURE_RESOURCE_GROUP: node-resource-group-stage
  AZURE_APP_PLAN: node-action-plan-stage
  AZURE_LOCATION: '"Central US"'
  AZURE_WEBAPP_NAME: mynodeinfoexpressapp-stage
jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
