name: Deploy the application to Prod

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP_PROD: node-resource-group-prod
  AZURE_APP_PLAN_PROD: node-action-plan-prod
  AZURE_LOCATION_PROD: '"West US"'
  AZURE_WEBAPP_NAME_PROD: mynodeinfoexpressapp-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_PROD }}
          package: .
